---
title: "model_requirements"
author: "Don Li"
date: "03/06/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Model requirements

## Dependent variable:
We are predicting expected time of arrival in seconds.

## Datasets of evaluation:
We can choose testing of our model on one of three categories:

* Singapore - Car
* Jakarta - Car
* Jakarta - Motorcycle

My opinion is that we should do Singapore - Car. The reasons are:

* Singapore is a small city, the terrain is fairly uniform. In contrast, Jakarta is larger and has some rural/mountain regions.
* Car is much preferred over motorcycle because of the variability of the motorcyclists. Cars have to obey the road rules, but people in motorcycles can do shady things.

## Model inputs:

* latitude_origin
* longitude_origin
* latitude_destination
* longitude_destination
* hour_of_day
* day_of_week

So, I guess we don't need stuff like accuracy level of the ping or the bearing, since it isn't a model input. Don't need phone OS too.

## Prediction measure:

* RMSE

Although our prediction error is a squared loss function, we may consider other loss functions, such as all-or-nothing loss. This is because we want to get the best prediction on their testing set. Minimising a squared loss function may be better on average, but we would want all-or-nothing for their test set.

Another alternative is to use the L1 loss. If we think their testing set is relatively small, then L1 loss might be more robust.

## Dataset notes

* Data collected in April 2019, with 1 s sampling rate.

We have some contextual information:

* Accuracy level
* Bearing
* Speed
* Labels and trajectories 
* Phone OS

Since data is only April 2019, we do not need month/year information.

## Derived and external covariates

External measures

* Weather information
* Humidity
* Temperature
* Rain
* Visibility
* Holiday information

Derived measures

* Distance percentile for the trip
* Create categorical variable for abnormal ride (very far or very slow)
* Weekend vs weekday
* Work hour
* Rush hour; morning and afternoon
* Number of concurrent rides in 100, 500, 1000 meters


## Data cleaning

* Remove very long trips? Need some definition of long.
* Remove unreasonable speed to time/distance






